name: schedule
description: a schedule date.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  english_words: ^3.1.3
  flutter_webview_plugin:  ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/bg.jpg
  uses-material-design: true